# Generated by Django 4.1.4 on 2023-06-18 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actv_name', models.CharField(max_length=100, verbose_name='Type')),
                ('actv_description', models.TextField(verbose_name='Description')),
                ('actv_start_dt', models.DateField(auto_now=True, verbose_name='Start Date')),
                ('actv_current_status', models.CharField(max_length=100, verbose_name='Current Satus')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, verbose_name='Category name')),
                ('cat_description', models.CharField(max_length=1024, verbose_name='Category Description')),
            ],
        ),
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fshd_name', models.CharField(max_length=100, verbose_name='Type')),
                ('fhsd_date', models.DateField(auto_now=True, verbose_name='Finished Date')),
                ('fshd_task_id', models.CharField(max_length=50, verbose_name='Task id')),
            ],
        ),
        migrations.CreateModel(
            name='Suspended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spnd_name', models.CharField(max_length=100, verbose_name='Type')),
                ('spnd_description', models.TextField(verbose_name='Description')),
                ('spnd_start_dt', models.DateField(auto_now=True, verbose_name='Start Date')),
                ('spnd_finished_dt', models.DateField(auto_now=True, verbose_name='Start Date')),
                ('spnd_issu', models.TextField(verbose_name='Issu')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsk_object_id', models.PositiveIntegerField(auto_created=True, unique=True, verbose_name='Object Id')),
                ('tsk_header', models.CharField(max_length=255, verbose_name='Header')),
                ('tsk_title', models.CharField(max_length=255, verbose_name='Title')),
                ('tsk_content', models.TextField(verbose_name='Post')),
                ('tsk_publish_dt', models.DateField(auto_now=True, verbose_name='Published Date')),
                ('tsk_modified_dt', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('tsk_end_time', models.DateField(verbose_name='End Date')),
                ('tsk_is_finished', models.BooleanField(verbose_name='Is Finished')),
                ('tsk_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tsk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Category')),
                ('tsk_contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stf_id', models.CharField(max_length=200, verbose_name='Stuff ID')),
                ('stf_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.task', verbose_name='Task Title')),
            ],
        ),
    ]
