# Generated by Django 4.2.2 on 2023-06-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_task_tsk_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tsk_contentType',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tsk_object_id',
        ),
    ]
